### ISSUE TITLE
"Improve this page" on posts does not work

### ISSUE THREAD

**Issue by ghostcodekc** [HabibRh26/HabibRh26.github.io#1]
On your posts, at the bottom it says "Improve this page" it has the incorrect URL format. Try clicking on it.

Go to this page: https://www.habib25cseju.me/posts/github/github_for_babies_1/ then at the bottom click "improve this page"

**Comment by HabibRh26** [comment]
> On your posts, at the bottom it says "Improve this page" it has the incorrect URL format. Try clicking on it.
> 
> Go to this page: https://www.habib25cseju.me/posts/github/github_for_babies_1/ then at the bottom click "improve this page"

Thanks, @ghostcodekc for reporting. I resolved this issue just now. Hope it works now.
